# github源
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'XNavigationBar_Example' do
  pod 'XNavigationBar', :path => '../'

  pod 'TZImagePickerController', '~> 3.2.9'
  
end
